"base_path" : "/app/src"
#"base_url" : ""

#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "/main/res/values/strings.xml",
  "dest" : "/strings.xml",
  "translation" : "/main/res/values-%android_code%/%original_file_name%"
 }
 {
  "source" : "/main/res/values/array.xml",
  "dest" : "/array.xml",
  "translation" : "/main/res/values-%android_code%/%original_file_name%"
 }
]